/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ajtkownklylxcdpnpzpm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdGtvd25rbHlseGNkcG5wenBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczODM3NzUsImV4cCI6MjA5Mjk1OTc3NX0.Nr689wCLvHOd0jojpJZOUXYw5xV0-m-JDBkd7TfKDDg"